### ISSUE TITLE
Add a rate limit

### ISSUE THREAD

**Issue by dave9123** [RohanGhalib/publicnotepad#1]
Add a rate limit to prevent users from spamming tons of notes in a certain period.

**Comment by RohanGhalib** [comment]
Hey dave! i think adding a limit to it will just make this project useless as it is solely based on concept of free will. anyways i added an algorithm in sidebar which will show the most visited notes on top rather than just showing recent notes.

**Comment by dave9123** [comment]
> Hey dave! i think adding a limit to it will just make this project useless as it is solely based on concept of free will. anyways i added an algorithm in sidebar which will show the most visited notes on top rather than just showing recent notes.

The concept of freewill must be set to a certain extent, a malicious actor might go ahead and spam random notes. I recommend you to add captcha such as reCAPTCHA.
